
INSERT INTO PRODUCT_LIST (NAME,ACCESS_CODE,VISIBLE,SHOW_ORDER,SERVICE_TYPE,GROUP_ID) VALUES 
('100 MB US Data Top-Up', 'DCUS100MB', 1, 1, 2, 'CAPROAMUS'),
	('1 GB US Data Top-Up', 'DCUS1GB', 0, 4, 0, 'CAPROAMUS'),
	('250 MB US Data Top-Up', 'DCUS250MB', 1, 2, 2, 'CAPROAMUS'),
	('500 MB US Data Top-Up', 'DCUS500MB', 1, 3, 2, 'CAPROAMUS'),
	('1 GB Data Top-Up', 'DPTOPUP', 1, 1, 0, 'DPTOPUPS'),
	('1 GB Data Top-Up', 'DPTOPUP1', 1, 2, 0, 'DPTOPUPS'),
	('1 GB Data Top-Up Shared', 'DPTOPUP1SH', 1, 1, 1, 'DPTOPUPS'),
	('2 GB Data Top-Up', 'DPTOPUP2', 1, 4, 0, 'DPTOPUPS'),
	('2 GB Data Top-Up', 'DPTOPUP2GB', 1, 3, 0, 'DPTOPUPS'),
	('2 GB Data Top-Up Shared', 'DPTOPUP2GBSH', 1, 3, 1, 'DPTOPUPS'),
	('2 GB Data Top-Up Shared', 'DPTOPUP2GBSHV', 1, 3, 1, 'DPTOPUPSV'),
	('2 GB Data Top-Up', 'DPTOPUP2GBV', 1, 3, 0, 'DPTOPUPSV'),
	('2 GB Data Top-Up Shared', 'DPTOPUP2SH', 1, 4, 1, 'DPTOPUPS'),
	('300 MB Data Top-Up', 'DPTOPUP300MB', 0, 1, 0, 'DPTOPUPS'),
	('300 MB Data Top-Up Shared', 'DPTOPUP300MBSH', 0, 1, 1, 'DPTOPUPS'),
	('300 MB Data Top-Up Shared', 'DPTOPUP300MBSHV', 0, 1, 1, 'DPTOPUPSV'),
	('300 MB Data Top-Up', 'DPTOPUP300MBV', 0, 1, 0, 'DPTOPUPSV'),
	('1 GB Data Top-Up Shared', 'DPTOPUPSH', 1, 2, 1, 'DPTOPUPS'),
	('1 GB Data Top-Up Shared', 'DPTOPUPSHV', 1, 2, 1, 'DPTOPUPSV'),
	('1 GB Data Top-Up', 'DPTOPUPV', 1, 2, 0, 'DPTOPUPSV'),
	('2 GB Data Top-Up Shared', 'FRTOPUP2GBSHV', 1, 4, 1, 'FRTOPUPSV'),
	('2 GB Data Top-Up', 'FRTOPUP2GBV', 1, 4, 0, 'FRTOPUPSV'),
	('Recharge de données 2 Go', 'FRTOPUP2SV', 1, 3, 1, 'FRTOPUPSV'),
	('Recharge de données 2 Go', 'FRTOPUP2V', 1, 3, 0, 'FRTOPUPSV'),
	('300 GB Data Top-Up Shared', 'FRTOPUP300MBSHV', 0, 5, 1, 'FRTOPUPSV'),
	('300 GB Data Top-Up', 'FRTOPUP300MBV', 0, 5, 0, 'FRTOPUPSV'),
	('Recharge de données 300 Mo', 'FRTOPUP3SV', 1, 1, 1, 'FRTOPUPSV'),
	('Recharge de données 300 Mo', 'FRTOPUP3V', 1, 1, 0, 'FRTOPUPSV'),
	('Recharge de données 1 Go', 'FRTOPUPSHV', 1, 2, 1, 'FRTOPUPSV'),
	('Recharge de données 1 Go', 'FRTOPUPV', 1, 2, 0, 'FRTOPUPSV'),
	('Trousse de voyage É.-U. 100 Mo', 'FRUS100MB', 1, 1, 0, 'FRROAMUS'),
	('1 GB US Data Top-Up', 'FRUS1GB', 1, 4, 0, 'FRROAMUS'),
	('Trousse de voyage É.-U. 250 Mo', 'FRUS250MB', 1, 2, 0, 'FRROAMUS'),
	('Trousse de voyage É.-U. 500 Mo', 'FRUS500MB', 1, 3, 0, 'FRROAMUS'),
	('100 MB US Data Top-Up', 'RUS100MB', 1, 1, 2, 'Da'),
	('100 MB US Data Top-Up', 'RUS100MBOT', 1, 2, 2, 'ROAMUS');